package keygen

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/grovetools/tuimux"
)

// TuimuxBinding represents a single keybinding to generate for tuimux.
type TuimuxBinding struct {
	Key            string
	Command        string
	Style          string // "popup" (default), "run-shell"
	Width          string
	Height         string
	X              string
	Y              string
	ExitOnComplete bool
}

// TuimuxConfig holds the configuration for generating tuimux keybindings.
type TuimuxConfig struct {
	LeaderKey string
	Bindings  []TuimuxBinding
}

// GenerateGlobalBindings converts TuimuxBindings into tuimux GlobalBindingConfig map.
func (c *TuimuxConfig) GenerateGlobalBindings() map[string]tuimux.GlobalBindingConfig {
	result := make(map[string]tuimux.GlobalBindingConfig)
	for _, b := range c.Bindings {
		style := b.Style
		if style == "" {
			style = "popup"
		}
		cfg := tuimux.GlobalBindingConfig{
			Command:        b.Command,
			Style:          style,
			ExitOnComplete: b.ExitOnComplete,
		}
		if style == "popup" {
			if b.Width != "" {
				cfg.Width = b.Width
			}
			if b.Height != "" {
				cfg.Height = b.Height
			}
			if b.X != "" {
				cfg.X = b.X
			}
			if b.Y != "" {
				cfg.Y = b.Y
			}
		}
		result[b.Key] = cfg
	}
	return result
}

// GenerateTOML produces a TOML string containing [keybindings.global.*] sections.
func (c *TuimuxConfig) GenerateTOML() string {
	var sb strings.Builder
	sb.WriteString("# Grove tuimux keybinding configuration\n")
	sb.WriteString("# Generated by: grove keys generate tuimux\n")
	sb.WriteString(fmt.Sprintf("# Last updated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("\n")

	if c.LeaderKey != "" {
		sb.WriteString(fmt.Sprintf("[keybindings]\nleader = %q\n\n", c.LeaderKey))
	}

	bindings := c.GenerateGlobalBindings()

	keys := make([]string, 0, len(bindings))
	for k := range bindings {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		cfg := bindings[key]
		sb.WriteString(fmt.Sprintf("[keybindings.global.%q]\n", key))
		sb.WriteString(fmt.Sprintf("command = %q\n", cfg.Command))
		sb.WriteString(fmt.Sprintf("style = %q\n", cfg.Style))

		if cfg.Style == "popup" {
			if cfg.Width != "" {
				sb.WriteString(fmt.Sprintf("width = %q\n", cfg.Width))
			}
			if cfg.Height != "" {
				sb.WriteString(fmt.Sprintf("height = %q\n", cfg.Height))
			}
			if cfg.X != "" {
				sb.WriteString(fmt.Sprintf("x = %q\n", cfg.X))
			}
			if cfg.Y != "" {
				sb.WriteString(fmt.Sprintf("y = %q\n", cfg.Y))
			}
		}

		if cfg.ExitOnComplete {
			sb.WriteString("exit_on_complete = true\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}
