# GitHub Dark High Contrast — grove palette for the "github" family.
# Derived from GitHub Primer primitives (primer/primitives) design tokens:
#   src/tokens/base/color/dark/dark.json5 + dark.high-contrast.json5 (base overrides)
#   src/tokens/functional/color/fgColor.json5 / bgColor.json5 / borderColor.json5
# Functional tokens resolved for theme "dark-high-contrast"
#   (overrides[theme] ?? overrides[dark] ?? $value).
# Mapping: bg=bgColor-default, bg_dark=bgColor-inset, bg_highlight=bgColor-muted,
#   fg=fgColor-default, comment=fgColor-muted,
#   border=borderColor-default, blue=fgColor-accent, green=fgColor-success,
#   yellow=fgColor-attention, orange=fgColor-severe, red=fgColor-danger,
#   purple=fgColor-done, magenta=fgColor-sponsors.
# bg_dark == bg (#010409): bgColor-inset resolves to base neutral.0 here, same as
#   bgColor-default — faithful to the tokens (high contrast flattens surfaces).
# cyan: current primitives has no cyan scale; substituted base.color.blue.2 (#91cbff),
#   a lighter blue-scale step distinct from fgColor-accent (#74b9ff).
# bg_visual omitted: bgColor-accent-muted is alpha-translucent in this token set.
# fg_inverse omitted (loader derives bg_dark): fgColor-onEmphasis is white here,
#   tuned for primer's gray emphasis surfaces, not for text on bright accents.
# SPDX-License-Identifier: MIT

[meta]
name = "github-dark-high-contrast"
family = "github"
variant = "dark-high-contrast"
appearance = "dark"
upstream = "https://github.com/primer/primitives"
author = "GitHub, Inc. (Primer)"
license = "MIT"

[palette]
bg = "#010409"
bg_dark = "#010409"
bg_highlight = "#151b23"
fg = "#ffffff"
comment = "#b7bdc8"
border = "#b7bdc8"
red = "#ff9492"
green = "#2bd853"
yellow = "#f0b72f"
blue = "#74b9ff"
magenta = "#ff90c8"
cyan = "#91cbff"
orange = "#fe9a2d"
purple = "#d3abff"

[palette.git]
add = "#2bd853"
change = "#f0b72f"
delete = "#ff9492"

[palette.diagnostics]
error = "#ff9492"
warning = "#f0b72f"
info = "#74b9ff"
