# Gruvbox (light, hard contrast) — g:gruvbox_contrast_light = "hard".
# Derived from gruvbox-community/gruvbox colors/gruvbox.vim (palette dict +
# light-mode role assignments; originally by Pavel Pertsev).
# Identical to gruvbox-light except bg=light0_hard (the contrast axis only
# changes bg0). bg_dark reuses light0_hard: gruvbox defines nothing brighter.
# Role mapping and terminal colors: see gruvbox-light.toml.
# SPDX-License-Identifier: MIT

[meta]
name = "gruvbox-light-hard"
family = "gruvbox"
variant = "light-hard"
appearance = "light"
upstream = "https://github.com/gruvbox-community/gruvbox"
author = "Pavel Pertsev (morhetz) and the gruvbox community"
license = "MIT"

[palette]
bg = "#f9f5d7"
bg_dark = "#f9f5d7"
bg_highlight = "#ebdbb2"
bg_visual = "#bdae93"
fg = "#3c3836"
fg_dark = "#504945"
fg_gutter = "#a89984"
comment = "#928374"
border = "#bdae93"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#b16286"
cyan = "#427b58"
orange = "#af3a03"
purple = "#8f3f71"

[palette.git]
add = "#79740e"
change = "#427b58"
delete = "#9d0006"

[terminal]
black = "#f9f5d7"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#7c6f64"
black_bright = "#928374"
red_bright = "#9d0006"
green_bright = "#79740e"
yellow_bright = "#b57614"
blue_bright = "#076678"
magenta_bright = "#8f3f71"
cyan_bright = "#427b58"
white_bright = "#3c3836"
