# Gruvbox (dark, hard contrast) — g:gruvbox_contrast_dark = "hard".
# Derived from gruvbox-community/gruvbox colors/gruvbox.vim (palette dict +
# dark-mode role assignments; originally by Pavel Pertsev).
# Identical to gruvbox-dark except bg=dark0_hard (the contrast axis only
# changes bg0). bg_dark reuses dark0_hard: gruvbox defines nothing darker.
# Role mapping and terminal colors: see gruvbox-dark.toml.
# SPDX-License-Identifier: MIT

[meta]
name = "gruvbox-dark-hard"
family = "gruvbox"
variant = "dark-hard"
appearance = "dark"
upstream = "https://github.com/gruvbox-community/gruvbox"
author = "Pavel Pertsev (morhetz) and the gruvbox community"
license = "MIT"

[palette]
bg = "#1d2021"
bg_dark = "#1d2021"
bg_highlight = "#3c3836"
bg_visual = "#665c54"
fg = "#ebdbb2"
fg_dark = "#d5c4a1"
fg_gutter = "#7c6f64"
comment = "#928374"
border = "#665c54"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
orange = "#fe8019"
purple = "#b16286"

[palette.git]
add = "#b8bb26"
change = "#8ec07c"
delete = "#fb4934"

[terminal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
black_bright = "#928374"
red_bright = "#fb4934"
green_bright = "#b8bb26"
yellow_bright = "#fabd2f"
blue_bright = "#83a598"
magenta_bright = "#d3869b"
cyan_bright = "#8ec07c"
white_bright = "#ebdbb2"
