# OneDark (deep) — grove palette.
# Derived from navarasu/onedark.nvim lua/onedark/palette.lua (variant "deep").
# Role mapping: bg=bg0, bg_dark=bg_d, bg_highlight=bg1, bg_visual=bg2, fg=fg,
# fg_dark=light_grey, fg_gutter=grey, comment=grey, border=bg3.
# magenta=purple: the onedark palette has no separate magenta accent, so the
# purple value is duplicated into the magenta slot.
# git/diagnostics/terminal omitted: the palette's diff_* colors are background
# tints, not foreground accents, so the loader derives those roles.
# SPDX-License-Identifier: MIT

[meta]
name = "onedark-deep"
family = "onedark"
variant = "deep"
appearance = "dark"
upstream = "https://github.com/navarasu/onedark.nvim"
author = "Navarasu"
license = "MIT"

[palette]
bg = "#1a212e"
bg_dark = "#141b24"
bg_highlight = "#21283b"
bg_visual = "#283347"
fg = "#93a4c3"
fg_dark = "#6c7d9c"
fg_gutter = "#455574"
comment = "#455574"
border = "#2a324a"
red = "#f65866"
green = "#8bcd5b"
yellow = "#efbd5d"
blue = "#41a7fc"
magenta = "#c75ae8"
cyan = "#34bfd0"
orange = "#dd9046"
purple = "#c75ae8"
