// Command icongen generates the name → icon lookup table for core/tui/theme.
//
// The theme exports ~150 icons as package variables, which is fine for Go code
// (theme.IconGitBranch is a compile-time check) and useless for everything
// else: a plugin manifest naming an icon, a protocol frame carrying one, a
// config file choosing one. Those need a lookup by string, and hand-writing a
// 150-entry map next to a 150-entry var block guarantees the two drift.
//
// It emits pointers, not values. The exported variables are reassigned in
// place when the icon mode switches (applyIcons), so a table of values would
// hand out Nerd Font glyphs to a terminal that had already switched to ASCII.
//
// Usage: go generate ./tui/theme/...
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	sourceFile = "icons.go"
	outputFile = "icons_table.go"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "icongen:", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, sourceFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parsing %s: %w", sourceFile, err)
	}

	names := exportedIconVars(file)
	if len(names) == 0 {
		return fmt.Errorf("no exported Icon* string variables found in %s; "+
			"has the declaration shape changed?", sourceFile)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by tools/icongen. DO NOT EDIT.

package %s

// iconTable maps a name, reduced to lowercase alphanumerics, to the exported
// variable holding that icon. The key is separator-free so every spelling a
// caller might use converges on one entry; iconNames carries the canonical
// hyphenated form for display.
//
// Pointers, not values: applyIcons reassigns the variables in place when the
// icon mode changes, so a table of values would keep handing out the set that
// was loaded when this map was built.
var iconTable = map[string]*string{
`, file.Name.Name)

	for _, name := range names {
		fmt.Fprintf(&buf, "\t%q: &%s,\n", stripped(strings.TrimPrefix(name, "Icon")), name)
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// iconNames is every icon name in canonical hyphenated form, in\n" +
		"// declaration order. This is the spelling a manifest or wire frame should\n" +
		"// use.\nvar iconNames = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&buf, "\t%q,\n", hyphenate(strings.TrimPrefix(name, "Icon")))
	}
	buf.WriteString("}\n")

	return os.WriteFile(outputFile, buf.Bytes(), 0o644)
}

// exportedIconVars returns every top-level `IconXxx string` variable, in
// declaration order.
func exportedIconVars(file *ast.File) []string {
	var names []string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			value, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			ident, ok := value.Type.(*ast.Ident)
			if !ok || ident.Name != "string" {
				continue
			}
			for _, name := range value.Names {
				if strings.HasPrefix(name.Name, "Icon") && name.Name != "Icon" && ast.IsExported(name.Name) {
					names = append(names, name.Name)
				}
			}
		}
	}
	return names
}

// stripped reduces a variable suffix to lowercase alphanumerics, matching what
// theme.normalizeIconName does to a lookup key. The two must agree, or a name
// that looks right will not resolve.
func stripped(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r - 'A' + 'a')
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		}
	}
	return b.String()
}

// hyphenate turns a CamelCase variable suffix into the canonical wire
// spelling: lowercase with word boundaries as hyphens. GitBranch -> git-branch.
func hyphenate(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if r >= 'A' && r <= 'Z' {
			// A boundary is a capital that follows a lowercase or digit, or
			// one that starts a new word after a run of capitals (HTTPServer
			// -> http-server).
			if i > 0 && (!isUpper(runes[i-1]) || (i+1 < len(runes) && !isUpper(runes[i+1]))) {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
			continue
		}
		b.WriteRune(r)
	}
	return strings.Trim(b.String(), "-")
}

func isUpper(r rune) bool { return r >= 'A' && r <= 'Z' }
